[docker-official]
host = "registry-1.docker.io"
username = ""
password = ""
scheme = "https"
[docker-mirror]
host = "hub-mirror.c.163.com"
username = ""
password = ""
scheme = "http"
[harbor]
host = "harbor.com:11180"
username = "admin"
password = "H@rb0rP@ss2d"
scheme = "http"