# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [ "ubuntu-py37", "ubuntu-py38", "ubuntu-py39", "ubuntu-py310" ]
        include:
          - name: "ubuntu-py37"
            python: "3.7"
            os: ubuntu-latest
            tox_env: "py37"
          - name: "ubuntu-py38"
            python: "3.8"
            os: ubuntu-latest
            tox_env: "py38"
          - name: "ubuntu-py39"
            python: "3.9"
            os: ubuntu-latest
            tox_env: "py39"
          - name: "ubuntu-py310"
            python: "3.10"
            os: ubuntu-latest
            tox_env: "py310"
            use_linter: true
            use_coverage: true

    steps:
    - uses: actions/checkout@v3
    - name: install poetry
      run: python -m pip install -U pip
           python -m pip install poetry tox coverage
    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: ${{ matrix.python }}
        cache: "poetry"
        
    - name: Install dep
      run: poetry install
      
    - name: Linter
      if: "matrix.use_linter"
      run: "tox -e ${{ matrix.tox_env }}-linter"

    - name: Test With Coverage
      if: "matrix.use_coverage"
      run: "tox -e ${{ matrix.tox_env }}-coverage"

    - name: Test without Coverage
      if: "! matrix.use_coverage"
      run: "tox -e ${{ matrix.tox_env }}-test"
